// SPDX-FileCopyrightText: 2024 Intel Corporation
// Copyright 2019 free5GC.org
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 *
 * AUSF Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"context"
	"fmt"
	"os"

	"github.com/omec-project/ausf/logger"
	"github.com/omec-project/ausf/service"
	"github.com/urfave/cli/v3"
)

var AUSF = &service.AUSF{}

func main() {
	app := &cli.Command{}
	app.Name = "ausf"
	logger.AppLog.Infoln(app.Name)
	app.Usage = "Authentication Server Function"
	app.UsageText = "ausf -cfg <ausf_config_file.conf>"
	app.Action = action
	app.Flags = AUSF.GetCliCmd()
	if err := app.Run(context.Background(), os.Args); err != nil {
		logger.AppLog.Fatalf("AUSF run error: %v", err)
	}
}

func action(ctx context.Context, c *cli.Command) error {
	if err := AUSF.Initialize(c); err != nil {
		logger.CfgLog.Errorf("%+v", err)
		return fmt.Errorf("failed to initialize")
	}

	AUSF.Start()

	return nil
}
