// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
AUSF API

AUSF UE Authentication Service.
© 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.4

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package ueauthentication

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/ausf/logger"
	"github.com/omec-project/ausf/producer"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/util/httpwrapper"
)

// Post /ue-authentications/:authCtxId/eap-session
func HTTPEapAuthMethod(c *gin.Context) {
	logger.EapAuthComfirmLog.Infoln("Handle Post /ue-authentications/:authCtxId/eap-session")
	var eapSessionReq models.EapSession

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		logger.EapAuthComfirmLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&eapSessionReq, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.EapAuthComfirmLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, eapSessionReq)
	req.Params["authCtxId"] = c.Param("authCtxId")

	rsp := producer.HandleEapAuthComfirmRequest(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.EapAuthComfirmLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Post /prose-authentications/:authCtxId/prose-auth
func HTTPProseAuth(c *gin.Context) {
	detail := "Handle Post /prose-authentications/:authCtxId/prose-auth is not implemented"
	logger.UeAuthPostLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Post /prose-authentications
func HTTPProseAuthenticationsPost(c *gin.Context) {
	detail := "Handle Post /prose-authentications is not implemented"
	logger.UeAuthPostLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Post /rg-authentications
func HTTPRgAuthenticationsPost(c *gin.Context) {
	detail := "Handle Post /rg-authentications is not implemented"
	logger.UeAuthPostLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Put /ue-authentications/:authCtxId/5g-aka-confirmation
func HTTPUeAuthenticationsAuthCtxId5gAkaConfirmationPut(c *gin.Context) {
	logger.Auth5gAkaComfirmLog.Infoln("Handle Put /ue-authentications/:authCtxId/5g-aka-confirmation")
	var confirmationData models.ConfirmationData

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		logger.Auth5gAkaComfirmLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&confirmationData, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.Auth5gAkaComfirmLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, confirmationData)
	req.Params["authCtxId"] = c.Param("authCtxId")

	rsp := producer.HandleAuth5gAkaComfirmRequest(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.Auth5gAkaComfirmLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Post /ue-authentications/deregister
func HTTPUeAuthenticationsDeregisterPost(c *gin.Context) {
	logger.UeAuthPostLog.Infoln("Handle Post /ue-authentications/deregister")
	var deregistrationInfo models.DeregistrationInfo

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		logger.UeAuthPostLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&deregistrationInfo, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.UeAuthPostLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, deregistrationInfo)
	rsp := producer.HandleUeAuthenticationsDeregisterRequest(req)
	if rsp.Body == nil {
		c.Status(rsp.Status)
		return
	}

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.UeAuthPostLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Post /ue-authentications
func HTTPUeAuthenticationsPost(c *gin.Context) {
	logger.UeAuthPostLog.Infoln("Handle Post /ue-authentications")
	var authInfo models.AuthenticationInfo

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		logger.UeAuthPostLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&authInfo, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.UeAuthPostLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, authInfo)

	rsp := producer.HandleUeAuthPostRequest(req)

	for key, value := range rsp.Header {
		c.Header(key, value[0])
	}
	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.UeAuthPostLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}
